import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarLine from "@/components/navbar/NavbarLine";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-0">
        <NavbarLine />
        {children}
      </body>
    </html>
  );
}
